stages:
  - "lint"
  - "build"
  - "deploy"

default:
  image: "node:lts"
  before_script:
    - "npm install"
  cache:
    paths:
      - "./node_modules/"

lint:
  stage: "lint"
  script:
    - "npm run lint"
  cache:
    paths:
      - "./node_modules/"

build:
  stage: "build"
  script:
    - "npm run build"
  artifacts:
    expire_in: "1 hour"
    paths:
      - "./dist/"

pages:
  stage: "deploy"
  only:
    - "page"
  script:
    - "rm -rf ./public/"
    - "mv ./dist/ ./public/"
  artifacts:
    paths:
      - "./public/"
