image: node:10-stretch

stages:
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

build:dev:
  stage: build
  script:
    - npm run build:dev
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/dev/

build:prod:
  stage: build
  script:
    - npm run build:prod
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/prod/
  only:
    - page

pages:
  stage: deploy
  script:
    - cp -r dist/prod/ public/
  artifacts:
    paths:
      - public/
  only:
    - page
