image: node:10-stretch

stages:
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - cp -r dist/ public/
  artifacts:
    paths:
      - public/
  only:
    - page
