stages:
  - 'lint'
  - 'build'
  - 'deploy'

default:
  image: 'docker.io/node:lts'
  cache:
    key:
      files:
        - './package-lock.json'
    paths:
      - './node_modules/'

lint:
  stage: 'lint'
  script:
    - 'npm ci'
    - 'npm run lint'

build:
  stage: 'build'
  needs:
    - 'lint'
  script:
    - 'npm ci'
    - 'npm run build'
  artifacts:
    expire_in: '1 hour'
    paths:
      - './dist/'

pages:
  stage: 'deploy'
  needs:
    - 'build'
  rules:
    - if: '$CI_COMMIT_BRANCH == "publish"'
  script:
    - 'rm -rf ./public/'
    - 'mv ./dist/ ./public/'
  artifacts:
    paths:
      - './public/'
