name: 'Build'

on:
  push:
    branches: ['*', '!publish']
  pull_request:
    branches: ['*', '!publish']

jobs:

  build:
    name: 'Build'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Checkout project'
        uses: 'actions/checkout@v2'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '16'
      - name: 'Cache node modules'
        uses: 'actions/cache@v2'
        with:
          key: "node-modules-${{hashFiles('**/package-lock.json')}}-${{runner.os}}"
          path: './node_modules/'
      - name: 'Install dependencies'
        run: |
          npm ci
      - name: 'Lint'
        run: |
          npm run lint
      - name: 'Build'
        run: |
          npm run build
