name: 'CI'

on:
  push:
    branches: ['*', '!publish']
  pull_request:
    branches: ['*', '!publish']
  workflow_dispatch:

jobs:

  build:
    name: 'Node.js ${{matrix.node_version}} on ${{matrix.os}}'
    runs-on: '${{matrix.os}}'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node_version: ['16']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js ${{matrix.node_version}}'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '${{matrix.node_version}}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Lint'
        run: 'npm run lint'
      - name: 'Build'
        run: 'npm run build'
