name: 'Cloudflare Pages'

on:
  push:
    branches: ['dist']
  workflow_dispatch:

jobs:

  pages:
    name: 'Cloudflare Pages'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      deployments: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Publish'
        uses: 'cloudflare/pages-action@1'
        with:
          accountId: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          apiToken: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          gitHubToken: '${{ secrets.GITHUB_TOKEN }}'
          projectName: 'hectorm'
          directory: './'
