name: 'Publish'

on:
  push:
    branches: ['publish']
  workflow_dispatch:

jobs:

  publish:
    name: 'Node.js ${{matrix.node_version}} on ${{matrix.os}}'
    runs-on: '${{matrix.os}}'
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node_version: ['16']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Use Node.js ${{matrix.node_version}}'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '${{matrix.node_version}}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Lint'
        run: 'npm run lint'
      - name: 'Build'
        run: 'npm run build'
      - name: 'Publish'
        run: |
          branch='dist'; dir='./dist/'; commit='no'
          git config user.name 'hectorm-bot'
          git config user.email 'noreply@molinero.dev'
          if git ls-remote --exit-code origin refs/heads/"${branch:?}"; then
            git fetch --force origin "${branch:?}":"${branch:?}"
            git symbolic-ref HEAD refs/heads/"${branch:?}"
            git --work-tree "${dir:?}" reset --mixed
            git --work-tree "${dir:?}" add --all
            ret='0'; git --work-tree "${dir:?}" diff --exit-code HEAD -- || ret="$?"
            if [ "${ret:?}" = '1' ]; then commit='yes'; fi
          else
            git --work-tree "${dir:?}" checkout --orphan "${branch:?}"
            git --work-tree "${dir:?}" add --all
            commit='yes'
          fi
          if [ "${commit:?}" = 'yes' ]; then
            git --work-tree "${dir:?}" commit -m "Deploy $(date -Iseconds)"
            git push origin "${branch:?}"
          fi
